version: "3.8"
services:
  url-shortener:
    image: gitlab.enterpriselab.ch:4567/enlab-22-fs011/g3/url-shortener:main
    container_name: url-shortener
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend_net
    depends_on:
      - db

  db:
    build: ./docker/hsqldb-image/
    container_name: url-shortener-db
    restart: always
    volumes:
      - 'hsqldb_data:/opt/hsqldb-2.6.1/hsqldb/data'
    networks:
      - backend_net

volumes:
  hsqldb_data:

networks:
  backend_net:
    driver: bridge

